Repository MAKE-VALUE-GACHI/1_CodeBrew_Front, pull requests merged in 2025-07, with the labels that each got.

#12 Feat(#7): Add Common NavBar && ToolTip && ProgressBar
  public/icons/profile.png
  src/app/ui-examples/page.tsx
  src/components/commons/NavBar/index.tsx
  src/components/commons/ProgressBar/index.tsx
  src/components/commons/ToolTip/index.tsx
  src/types/components/commons/NavBar.ts
  src/types/components/commons/ProgressBar.ts
  src/types/components/commons/ToolTip.ts
Labels: 🧑🏻‍🎨 Style, 🛠️ Feat

#13 Feat(#7): 공통 컴포넌트: 버튼, 메뉴 아이템, 드랍다운, 카드, 체크박스
  package-lock.json
  package.json
  public/icons/checked.svg
  public/icons/circleX.svg
  public/icons/eyeCrossLine.svg
  public/icons/eyeOpen.svg
  public/icons/uncheck.svg
  public/icons/under.svg
  src/app/globals.css
  src/app/ui-examples/page.tsx
  src/components/commons/Button/index.tsx
  src/components/commons/Card/index.tsx
  src/components/commons/Chat/index.tsx
  src/components/commons/CheckBox/index.tsx
  src/components/commons/DropDown/index.tsx
  src/components/commons/Input/index.tsx
  src/components/commons/Input/inputDeleteIcon.tsx
  src/components/commons/Input/inputVisibleIcon.tsx
  src/components/commons/MenuItem/index.tsx
  src/components/commons/UnderlineButton/index.tsx
  src/constants/design.ts
  src/types/components/commons/Button.ts
  src/types/components/commons/Card.ts
  src/types/components/commons/CheckBox.ts
  src/types/components/commons/DropDown.ts
  src/types/components/commons/MenuItem.ts
  src/types/components/commons/UnderlineButton.ts
  src/types/components/commons/input/index.ts
  src/types/components/commons/input/inputDeleteIcon.ts
  src/types/components/commons/input/inputVisibleIcon.ts
  tailwind.config.ts
Labels: 🛠️ Feat

#18 Feat(#17): sign 공통 레이아웃 구현 & RHF 라이브러리 설치
  package-lock.json
  package.json
  src/app/(auth)/layout.tsx
  src/app/(auth)/sign-in/page.tsx
  src/app/(auth)/sign-up/page.tsx
Labels: 🏗️ Chore, 🛠️ Feat
