Repository MAKE-VALUE-GACHI/1_CodeBrew_Front, pull requests merged in 2025-06, with the labels that each got.

#3 Feat(#2) eslint prettier husky setup
  .husky/pre-commit
  .prettierrc
  eslint.config.mjs
  package-lock.json
  package.json
  src/app/layout.tsx
Labels: 🛠️ Feat

#5 Docs(#1): Add GitHub templates
  .github/ISSUE_TEMPLATE/♻️-refactor.md
  .github/ISSUE_TEMPLATE/🐞-bug.md
  .github/ISSUE_TEMPLATE/🛠️-feature.md
  .github/pull_request_template.md
Labels: 📜 Docs

#6 Chore(#4): 라이브러리들 설치
  .github/ISSUE_TEMPLATE/♻️-refactor.md
  .github/ISSUE_TEMPLATE/🐞-bug.md
  .github/ISSUE_TEMPLATE/🛠️-feature.md
  .github/pull_request_template.md
  package-lock.json
  package.json
Labels: 🏗️ Chore
